version: "3.8"

services:
  backend:
    image: amineyagoub/api-api:latest
    container_name: backend
    restart: always
    ports:
      - "3010:3000"
    working_dir: /app
    networks:
      - app-network

  frontend:
    image: amineyagoub/app-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    working_dir: /app
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
