name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy-frontend:
    name: Build and Deploy frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          file: docker/ui/Dockerfile
          cache-from: type=registry,ref=amineyagoub/app-frontend:latest
          cache-to: type=inline
          tags: amineyagoub/app-frontend:latest

  build-and-deploy-api:
    name: Build and Deploy api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          file: docker/server/Dockerfile
          cache-from: type=registry,ref=amineyagoub/api-api:latest
          cache-to: type=inline
          tags: amineyagoub/api-api:latest
